namespace Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightStatusHistory.Infrastructure.Entity;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public sealed class FlightStatusHistoryEntityConfiguration
    : IEntityTypeConfiguration<FlightStatusHistoryEntity>
{
    public void Configure(EntityTypeBuilder<FlightStatusHistoryEntity> builder)
    {
        builder.ToTable("flight_status_history");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Id)
               .HasColumnName("flight_status_history_id")
               .ValueGeneratedOnAdd();

        builder.Property(e => e.ScheduledFlightId)
               .HasColumnName("scheduled_flight_id")
               .IsRequired();

        builder.Property(e => e.FlightStatusId)
               .HasColumnName("flight_status_id")
               .IsRequired();

        builder.Property(e => e.ChangedAt)
               .HasColumnName("changed_at")
               .HasColumnType("datetime(6)")
               .IsRequired()
               .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

        builder.Property(e => e.Notes)
               .HasColumnName("notes")
               .IsRequired(false)
               .HasMaxLength(250);

        builder.HasIndex(e => new { e.ScheduledFlightId, e.FlightStatusId, e.ChangedAt })
               .IsUnique()
               .HasDatabaseName("uq_fsh");

        // <AUTO-GENERATED-FK-RELATIONSHIPS>
        builder.HasOne<ScheduledFlightEntity>()
               .WithMany()
               .HasForeignKey(e => e.ScheduledFlightId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_fsh_flight");

        builder.HasOne<FlightStatusEntity>()
               .WithMany()
               .HasForeignKey(e => e.FlightStatusId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_fsh_status");
        // </AUTO-GENERATED-FK-RELATIONSHIPS>
}
}