namespace Sistema_de_gestion_de_tiquetes_Aereos.Modules.ScheduledFlight.Infrastructure.Entity;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public sealed class ScheduledFlightEntityConfiguration : IEntityTypeConfiguration<ScheduledFlightEntity>
{
    public void Configure(EntityTypeBuilder<ScheduledFlightEntity> builder)
    {
        builder.ToTable("scheduled_flight");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Id)
               .HasColumnName("scheduled_flight_id")
               .ValueGeneratedOnAdd();

        builder.Property(e => e.BaseFlightId)
               .HasColumnName("base_flight_id")
               .IsRequired();

        builder.Property(e => e.AircraftId)
               .HasColumnName("aircraft_id")
               .IsRequired();

        builder.Property(e => e.GateId)
               .HasColumnName("gate_id")
               .IsRequired(false);

        builder.Property(e => e.DepartureDate)
               .HasColumnName("departure_date")
               .IsRequired();

        builder.Property(e => e.DepartureTime)
               .HasColumnName("departure_time")
               .IsRequired();

        builder.Property(e => e.EstimatedArrivalDatetime)
               .HasColumnName("estimated_arrival_datetime")
               .IsRequired();

        builder.Property(e => e.FlightStatusId)
               .HasColumnName("flight_status_id")
               .IsRequired();

        builder.Property(e => e.CreatedAt)
               .HasColumnName("created_at")
               .HasColumnType("datetime(6)")
               .IsRequired()
               .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

        builder.Property(e => e.UpdatedAt)
               .HasColumnName("updated_at")
               .HasColumnType("datetime(6)")
               .IsRequired(false);

        builder.HasIndex(e => new { e.BaseFlightId, e.DepartureDate, e.DepartureTime })
               .IsUnique()
               .HasDatabaseName("uq_sf");

        // <AUTO-GENERATED-FK-RELATIONSHIPS>
        builder.HasOne<BaseFlightEntity>()
               .WithMany()
               .HasForeignKey(e => e.BaseFlightId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_sf_base_flight");

        builder.HasOne<AircraftEntity>()
               .WithMany()
               .HasForeignKey(e => e.AircraftId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_sf_aircraft");

        builder.HasOne<GateEntity>()
               .WithMany()
               .HasForeignKey(e => e.GateId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_sf_gate");

        builder.HasOne<FlightStatusEntity>()
               .WithMany()
               .HasForeignKey(e => e.FlightStatusId)
               .OnDelete(DeleteBehavior.Restrict)
               .HasConstraintName("fk_sf_status");
        // </AUTO-GENERATED-FK-RELATIONSHIPS>
}
}