// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_gestion_de_tiquetes_Aereos.Shared.Context;

#nullable disable

namespace Sistema_de_gestion_de_tiquetes_Aereos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421164422_ReservationStatus")]
    partial class ReservationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aircraft_id");

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int")
                        .HasColumnName("manufacture_year");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AircraftId")
                        .HasName("pk_aircraft");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_registration_number");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.AircraftManufacturer.Infrastructure.Entity.AircraftManufacturerEntity", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ManufacturerId")
                        .HasName("pk_aircraft_manufacturer");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_manufacturer_name");

                    b.ToTable("aircraft_manufacturer", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.AircraftType.Infrastructure.Entity.AircraftTypeEntity", b =>
                {
                    b.Property<int>("AircraftTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_id");

                    b.Property<decimal>("CargoCapacityKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cargo_capacity_kg");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("AircraftTypeId")
                        .HasName("pk_aircraft_type");

                    b.HasIndex("ManufacturerId", "Model")
                        .IsUnique()
                        .HasDatabaseName("uq_aircraft_type");

                    b.ToTable("aircraft_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Airline.Infrastructure.Entity.AirlineEntity", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("iata_code")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AirlineId")
                        .HasName("pk_airline");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("ix_airline_iata_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_airline_name");

                    b.ToTable("airline", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Airport.Infrastructure.Entity.AirportEntity", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("iata_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("AirportId")
                        .HasName("pk_airport");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("ix_airport_iata_code");

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.BaggageAllowance.Infrastructure.Entity.BaggageAllowanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("baggage_allowance_id");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_id");

                    b.Property<decimal>("CarryOnKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10m)
                        .HasColumnName("carry_on_kg");

                    b.Property<int>("CarryOnPieces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("carry_on_pieces");

                    b.Property<decimal>("CheckedKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("checked_kg");

                    b.Property<int>("CheckedPieces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("checked_pieces");

                    b.Property<int>("FareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fare_type_id");

                    b.HasKey("Id")
                        .HasName("pk_baggage_allowance");

                    b.HasIndex("CabinClassId", "FareTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_ba");

                    b.ToTable("baggage_allowance", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.BaggageType.Infrastructure.Entity.BaggageTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("baggage_type_id");

                    b.Property<decimal>("ExtraFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("extra_fee");

                    b.Property<decimal>("MaxWeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("max_weight_kg");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_baggage_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_baggage_type_name");

                    b.ToTable("baggage_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.BaseFlight.Infrastructure.Entity.BaseFlightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("base_flight_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("flight_code");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_base_flight");

                    b.HasIndex("FlightCode", "AirlineId")
                        .IsUnique()
                        .HasDatabaseName("uq_base_flight");

                    b.ToTable("base_flight", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.BoardingPass.Infrastructure.Entity.BoardingPassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("boarding_pass_id");

                    b.Property<string>("BoardingGroup")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("boarding_group");

                    b.Property<int>("CheckInId")
                        .HasColumnType("int")
                        .HasColumnName("check_in_id");

                    b.Property<int>("FlightSeatId")
                        .HasColumnType("int")
                        .HasColumnName("flight_seat_id");

                    b.Property<int?>("GateId")
                        .HasColumnType("int")
                        .HasColumnName("gate_id");

                    b.HasKey("Id")
                        .HasName("pk_boarding_pass");

                    b.HasIndex("CheckInId")
                        .IsUnique()
                        .HasDatabaseName("uq_boarding_pass_check_in");

                    b.ToTable("boarding_pass", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CabinClass.Infrastructure.Entity.CabinClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cabin_class");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_cabin_class_name");

                    b.ToTable("cabin_class", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CancellationReason.Infrastructure.Entity.CancellationReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cancellation_reason_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_reason");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_cancellation_reason_name");

                    b.ToTable("cancellation_reason", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CheckIn.Infrastructure.Entity.CheckInEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("check_in_id");

                    b.Property<int>("CheckInStatusId")
                        .HasColumnType("int")
                        .HasColumnName("check_in_status_id");

                    b.Property<DateTime>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("check_in_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("CounterNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("counter_number");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_check_in");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("uq_check_in_ticket");

                    b.ToTable("check_in", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CheckInStatus.Infrastructure.Entity.CheckInStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("check_in_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_check_in_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_check_in_status_name");

                    b.ToTable("check_in_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.City.Infrastructure.Entity.CityEntity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CityId")
                        .HasName("pk_city");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("uq_city");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.ContactType.Infrastructure.Entity.ContactTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contact_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_contact_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_contact_type_name");

                    b.ToTable("contact_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Country.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_country_name");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CrewRole.Infrastructure.Entity.CrewRoleEntity", b =>
                {
                    b.Property<int>("CrewRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crew_role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("CrewRoleId")
                        .HasName("pk_crew_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_crew_role_name");

                    b.ToTable("crew_role", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Currency.Infrastructure.Entity.CurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("iso_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("uq_currency_iso_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_currency_name");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Customer.Infrastructure.Entity.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_person_id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.DelayReason.Infrastructure.Entity.DelayReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delay_reason_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delay_reason");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_delay_reason_name");

                    b.ToTable("delay_reason", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.DiscountType.Infrastructure.Entity.DiscountTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discount_type_id");

                    b.Property<int?>("AgeMax")
                        .HasColumnType("int")
                        .HasColumnName("age_max");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("int")
                        .HasColumnName("age_min");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.HasKey("Id")
                        .HasName("pk_discount_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_discount_type_name");

                    b.ToTable("discount_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.DocumentType.Infrastructure.Entity.DocumentTypeEntity", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("DocumentTypeId")
                        .HasName("pk_document_type");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_document_type_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_document_type_name");

                    b.ToTable("document_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Employee.Infrastructure.Entity.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("int")
                        .HasColumnName("job_position_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employee");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_person_id");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FareType.Infrastructure.Entity.FareTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fare_type_id");

                    b.Property<int>("AdvancePurchaseDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("advance_purchase_days");

                    b.Property<bool>("BaggageIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("baggage_included");

                    b.Property<bool>("IsChangeable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_changeable");

                    b.Property<bool>("IsRefundable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_refundable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fare_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_fare_type_name");

                    b.ToTable("fare_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightCabinPrice.Infrastructure.Entity.FlightCabinPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_cabin_price_id");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_id");

                    b.Property<int>("FareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fare_type_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_cabin_price");

                    b.HasIndex("ScheduledFlightId", "CabinClassId", "FareTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_fcp");

                    b.ToTable("flight_cabin_price", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightCancellation.Infrastructure.Entity.FlightCancellationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cancellation_id");

                    b.Property<int>("CancellationReasonId")
                        .HasColumnType("int")
                        .HasColumnName("cancellation_reason_id");

                    b.Property<DateTime>("CancelledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notes");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_cancellation");

                    b.HasIndex("ScheduledFlightId")
                        .IsUnique()
                        .HasDatabaseName("uq_flight_cancellation_flight");

                    b.ToTable("flight_cancellation", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightCrew.Infrastructure.Entity.FlightCrewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_crew_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CrewRoleId")
                        .HasColumnType("int")
                        .HasColumnName("crew_role_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_crew");

                    b.HasIndex("ScheduledFlightId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("uq_fc_employee");

                    b.ToTable("flight_crew", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightDelay.Infrastructure.Entity.FlightDelayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_delay_id");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int")
                        .HasColumnName("delay_minutes");

                    b.Property<int>("DelayReasonId")
                        .HasColumnType("int")
                        .HasColumnName("delay_reason_id");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reported_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_delay");

                    b.ToTable("flight_delay", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightPromotion.Infrastructure.Entity.FlightPromotionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_promotion_id");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_promotion");

                    b.HasIndex("ScheduledFlightId", "PromotionId")
                        .IsUnique()
                        .HasDatabaseName("uq_fp");

                    b.ToTable("flight_promotion", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightSeat.Infrastructure.Entity.FlightSeatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_seat_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.Property<int>("SeatMapId")
                        .HasColumnType("int")
                        .HasColumnName("seat_map_id");

                    b.Property<int>("SeatStatusId")
                        .HasColumnType("int")
                        .HasColumnName("seat_status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_flight_seat");

                    b.HasIndex("ScheduledFlightId", "SeatMapId")
                        .IsUnique()
                        .HasDatabaseName("uq_flight_seat");

                    b.ToTable("flight_seat", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightStatus.Infrastructure.Entity.FlightStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_flight_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_flight_status_name");

                    b.ToTable("flight_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightStatusHistory.Infrastructure.Entity.FlightStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_status_history_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("FlightStatusId")
                        .HasColumnType("int")
                        .HasColumnName("flight_status_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notes");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_status_history");

                    b.HasIndex("ScheduledFlightId", "FlightStatusId", "ChangedAt")
                        .IsUnique()
                        .HasDatabaseName("uq_fsh");

                    b.ToTable("flight_status_history", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Gate.Infrastructure.Entity.GateEntity", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gate_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int")
                        .HasColumnName("terminal_id");

                    b.HasKey("GateId")
                        .HasName("pk_gate");

                    b.HasIndex("TerminalId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_gate");

                    b.ToTable("gate", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Gender.Infrastructure.Entity.GenderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_gender");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_gender_name");

                    b.ToTable("gender", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.JobPosition.Infrastructure.Entity.JobPositionEntity", b =>
                {
                    b.Property<int>("JobPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_position_id");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("JobPositionId")
                        .HasName("pk_job_position");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_position_name");

                    b.ToTable("job_position", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyAccount.Infrastructure.Entity.LoyaltyAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loyalty_account_id");

                    b.Property<int>("AvailableMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("available_miles");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("LoyaltyProgramId")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_program_id");

                    b.Property<int>("LoyaltyTierId")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_tier_id");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<int>("TotalMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_miles");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_account");

                    b.HasIndex("LoyaltyProgramId", "LoyaltyTierId")
                        .HasDatabaseName("ix_loyalty_account_loyalty_program_id_loyalty_tier_id");

                    b.HasIndex("PassengerId", "LoyaltyProgramId")
                        .IsUnique()
                        .HasDatabaseName("uq_la");

                    b.ToTable("loyalty_account", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyProgram.Infrastructure.Entity.LoyaltyProgramEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loyalty_program_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<decimal>("MilesPerDollar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("miles_per_dollar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_program");

                    b.HasIndex("AirlineId")
                        .IsUnique()
                        .HasDatabaseName("uq_loyalty_program_airline");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_loyalty_program_name");

                    b.ToTable("loyalty_program", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyTier.Infrastructure.Entity.LoyaltyTierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loyalty_tier_id");

                    b.Property<string>("Benefits")
                        .HasColumnType("longtext")
                        .HasColumnName("benefits");

                    b.Property<int>("LoyaltyProgramId")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_program_id");

                    b.Property<int>("MinMiles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("min_miles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_tier");

                    b.HasAlternateKey("LoyaltyProgramId", "Id")
                        .HasName("ak_loyalty_tiers_loyalty_program_id_id");

                    b.HasIndex("LoyaltyProgramId", "Id")
                        .IsUnique()
                        .HasDatabaseName("uq_lt_fk");

                    b.HasIndex("LoyaltyProgramId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_lt");

                    b.ToTable("loyalty_tier", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyTransaction.Infrastructure.Entity.LoyaltyTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loyalty_transaction_id");

                    b.Property<int>("LoyaltyAccountId")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_account_id");

                    b.Property<int>("Miles")
                        .HasColumnType("int")
                        .HasColumnName("miles");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_loyalty_transaction");

                    b.ToTable("loyalty_transaction", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Nationality.Infrastructure.Entity.NationalityEntity", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nationality_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Demonym")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("demonym");

                    b.HasKey("NationalityId")
                        .HasName("pk_nationality");

                    b.HasIndex("CountryId")
                        .IsUnique()
                        .HasDatabaseName("uq_nationality_country");

                    b.ToTable("nationality", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Passenger.Infrastructure.Entity.PassengerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FrequentFlyerNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("frequent_flyer_number");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int")
                        .HasColumnName("nationality_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_passenger");

                    b.HasIndex("FrequentFlyerNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_passenger_ffn")
                        .HasFilter("frequent_flyer_number IS NOT NULL");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("uq_passenger_person");

                    b.ToTable("passenger", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.PassengerContact.Infrastructure.Entity.PassengerContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_contact_id");

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int")
                        .HasColumnName("contact_type_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Relationship")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("relationship");

                    b.HasKey("Id")
                        .HasName("pk_passenger_contact");

                    b.HasIndex("PassengerId", "ContactTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_pc");

                    b.ToTable("passenger_contact", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.PassengerDiscount.Infrastructure.Entity.PassengerDiscountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_discount_id");

                    b.Property<decimal>("AmountApplied")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount_applied");

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("discount_type_id");

                    b.Property<int>("ReservationDetailId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_detail_id");

                    b.HasKey("Id")
                        .HasName("pk_passenger_discount");

                    b.HasIndex("ReservationDetailId", "DiscountTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_pd");

                    b.ToTable("passenger_discount", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Payment.Infrastructure.Entity.PaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("payment_status_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("rejection_reason");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.PaymentMethod.Infrastructure.Entity.PaymentMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_method");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_payment_method_name");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.PaymentStatus.Infrastructure.Entity.PaymentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_payment_status_name");

                    b.ToTable("payment_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Person.Infrastructure.Entity.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("DocumentTypeId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_person_document");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Promotion.Infrastructure.Entity.PromotionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<decimal>("DiscountPct")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_pct");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_promotion");

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Refund.Infrastructure.Entity.RefundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refund_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("reason");

                    b.Property<int>("RefundStatusId")
                        .HasColumnType("int")
                        .HasColumnName("refund_status_id");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id")
                        .HasName("pk_refund");

                    b.ToTable("refund", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.RefundStatus.Infrastructure.Entity.RefundStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refund_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_refund_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_refund_status_name");

                    b.ToTable("refund_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Reservation.Infrastructure.Entity.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reservation_code");

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reservation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_status_id");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("ReservationCode")
                        .IsUnique()
                        .HasDatabaseName("uq_reservation_code");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.ReservationDetail.Infrastructure.Entity.ReservationDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("FareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fare_type_id");

                    b.Property<int>("FlightSeatId")
                        .HasColumnType("int")
                        .HasColumnName("flight_seat_id");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reservation_detail");

                    b.HasIndex("ReservationId", "FlightSeatId")
                        .IsUnique()
                        .HasDatabaseName("uq_rd_seat");

                    b.HasIndex("ReservationId", "PassengerId")
                        .IsUnique()
                        .HasDatabaseName("uq_rd_passenger");

                    b.ToTable("reservation_detail", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.ReservationStatus.Infrastructure.Entity.ReservationStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_reservation_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_reservation_status_name");

                    b.ToTable("reservation_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.ReservationStatusHistory.Infrastructure.Entity.ReservationStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_status_history_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notes");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("reservation_status_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation_status_history");

                    b.HasIndex("ReservationId", "ReservationStatusId", "ChangedAt")
                        .IsUnique()
                        .HasDatabaseName("uq_rsh");

                    b.ToTable("reservation_status_history", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Route.Infrastructure.Entity.RouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("int")
                        .HasColumnName("destination_airport_id");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("int")
                        .HasColumnName("origin_airport_id");

                    b.HasKey("Id")
                        .HasName("pk_route");

                    b.HasIndex("OriginAirportId", "DestinationAirportId")
                        .IsUnique()
                        .HasDatabaseName("uq_route");

                    b.ToTable("route", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.RouteSchedule.Infrastructure.Entity.RouteScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_schedule_id");

                    b.Property<int>("BaseFlightId")
                        .HasColumnType("int")
                        .HasColumnName("base_flight_id");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("departure_time");

                    b.HasKey("Id")
                        .HasName("pk_route_schedule");

                    b.HasIndex("BaseFlightId", "DayOfWeek", "DepartureTime")
                        .IsUnique()
                        .HasDatabaseName("uq_rs");

                    b.ToTable("route_schedule", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.ScheduledFlight.Infrastructure.Entity.ScheduledFlightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_id");

                    b.Property<int>("BaseFlightId")
                        .HasColumnType("int")
                        .HasColumnName("base_flight_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("date")
                        .HasColumnName("departure_date");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("departure_time");

                    b.Property<DateTime>("EstimatedArrivalDatetime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("estimated_arrival_datetime");

                    b.Property<int>("FlightStatusId")
                        .HasColumnType("int")
                        .HasColumnName("flight_status_id");

                    b.Property<int?>("GateId")
                        .HasColumnType("int")
                        .HasColumnName("gate_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_flight");

                    b.HasIndex("BaseFlightId", "DepartureDate", "DepartureTime")
                        .IsUnique()
                        .HasDatabaseName("uq_sf");

                    b.ToTable("scheduled_flight", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.SeatMap.Infrastructure.Entity.SeatMapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_map_id");

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_id");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_id");

                    b.Property<string>("SeatFeatures")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("seat_features");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("seat_number");

                    b.HasKey("Id")
                        .HasName("pk_seat_map");

                    b.HasIndex("AircraftTypeId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_seat_map");

                    b.ToTable("seat_map", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.SeatStatus.Infrastructure.Entity.SeatStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seat_status_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_seat_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_seat_status_name");

                    b.ToTable("seat_status", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Terminal.Infrastructure.Entity.TerminalEntity", b =>
                {
                    b.Property<int>("TerminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("terminal_id");

                    b.Property<int>("AirportId")
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsInternational")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_international");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("TerminalId")
                        .HasName("pk_terminal");

                    b.HasIndex("AirportId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_terminal");

                    b.ToTable("terminal", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.TicketStatusHistory.Infrastructure.Entity.TicketStatusHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ticket_status_history_id");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notes");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_status_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_status_history");

                    b.HasIndex("TicketId", "TicketStatusId", "ChangedAt")
                        .IsUnique()
                        .HasDatabaseName("uq_tsh");

                    b.ToTable("ticket_status_history", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyAccount.Infrastructure.Entity.LoyaltyAccountEntity", b =>
                {
                    b.HasOne("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyTier.Infrastructure.Entity.LoyaltyTierEntity", "LoyaltyTier")
                        .WithMany("LoyaltyAccounts")
                        .HasForeignKey("LoyaltyProgramId", "LoyaltyTierId")
                        .HasPrincipalKey("LoyaltyProgramId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_account_loyalty_tiers_loyalty_program_id_loyalty_tie");

                    b.Navigation("LoyaltyTier");
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.LoyaltyTier.Infrastructure.Entity.LoyaltyTierEntity", b =>
                {
                    b.Navigation("LoyaltyAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
