// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_gestion_de_tiquetes_Aereos.Shared.Context;

#nullable disable

namespace Sistema_de_gestion_de_tiquetes_Aereos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420194513_Gate")]
    partial class Gate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Aircraft.Infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aircraft_id");

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int")
                        .HasColumnName("manufacture_year");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("registration_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AircraftId")
                        .HasName("pk_aircraft");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_registration_number");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.AircraftManufacturer.Infrastructure.Entity.AircraftManufacturerEntity", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ManufacturerId")
                        .HasName("pk_aircraft_manufacturer");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_manufacturer_name");

                    b.ToTable("aircraft_manufacturer", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.AircraftType.Infrastructure.Entity.AircraftTypeEntity", b =>
                {
                    b.Property<int>("AircraftTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_id");

                    b.Property<decimal>("CargoCapacityKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cargo_capacity_kg");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int")
                        .HasColumnName("total_seats");

                    b.HasKey("AircraftTypeId")
                        .HasName("pk_aircraft_type");

                    b.HasIndex("ManufacturerId", "Model")
                        .IsUnique()
                        .HasDatabaseName("uq_aircraft_type");

                    b.ToTable("aircraft_type", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Airline.Infrastructure.Entity.AirlineEntity", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airline_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("iata_code")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("AirlineId")
                        .HasName("pk_airline");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("ix_airline_iata_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_airline_name");

                    b.ToTable("airline", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Airport.Infrastructure.Entity.AirportEntity", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("iata_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("AirportId")
                        .HasName("pk_airport");

                    b.HasIndex("IataCode")
                        .IsUnique()
                        .HasDatabaseName("ix_airport_iata_code");

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.CancellationReason.Infrastructure.Entity.CancellationReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cancellation_reason_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_reason");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_cancellation_reason_name");

                    b.ToTable("cancellation_reason", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.City.Infrastructure.Entity.CityEntity", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("CityId")
                        .HasName("pk_city");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique()
                        .HasDatabaseName("uq_city");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Country.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_country_name");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.DelayReason.Infrastructure.Entity.DelayReasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delay_reason_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delay_reason");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_delay_reason_name");

                    b.ToTable("delay_reason", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightCancellation.Infrastructure.Entity.FlightCancellationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cancellation_id");

                    b.Property<int>("CancellationReasonId")
                        .HasColumnType("int")
                        .HasColumnName("cancellation_reason_id");

                    b.Property<DateTime>("CancelledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("notes");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_cancellation");

                    b.HasIndex("ScheduledFlightId")
                        .IsUnique()
                        .HasDatabaseName("uq_flight_cancellation_flight");

                    b.ToTable("flight_cancellation", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.FlightDelay.Infrastructure.Entity.FlightDelayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_delay_id");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int")
                        .HasColumnName("delay_minutes");

                    b.Property<int>("DelayReasonId")
                        .HasColumnType("int")
                        .HasColumnName("delay_reason_id");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reported_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("ScheduledFlightId")
                        .HasColumnType("int")
                        .HasColumnName("scheduled_flight_id");

                    b.HasKey("Id")
                        .HasName("pk_flight_delay");

                    b.ToTable("flight_delay", (string)null);
                });

            modelBuilder.Entity("Sistema_de_gestion_de_tiquetes_Aereos.Modules.Gate.Infrastructure.Entity.GateEntity", b =>
                {
                    b.Property<int>("GateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gate_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int")
                        .HasColumnName("terminal_id");

                    b.HasKey("GateId")
                        .HasName("pk_gate");

                    b.HasIndex("TerminalId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uq_gate");

                    b.ToTable("gate", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
